namespace Domain.Models
{
    /// <summary>
    /// A model class representing a menu item which can be related to one specific restaurant by means of the RestaurantId attribute.
    /// Each instance of thereof requires approval of the owner of the restaurant. 
    /// Once approved, the menu items will be visible to the public catalogue if and only if they approved by the restaurant owner.
    /// </summary>
    public class MenuItem
    {
        #region Definition of the attributes that constitute a menu item (what defines a menu item, such as its title, price, and which eatery serves this particular item).
        /// <summary>
        /// A unique identifier generated by Entity Framework Core, this attribute identifies each instance of MenuItem in the database.
        /// This will be generated in the DbContext class using a DEFAULT constraint whereby when no value is supplied to this attribute,
        /// a default value, in this case a Version 4 Universally Unique Identifier (otherwise simply known as UUID), is automatically used.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// This is not to be confused with the Id attribute. 
        /// The former denotes how instances will be uniquely identified in the SQL Server database.
        /// Whereas ExternalId stores the value associated with the "id" key in the JSON file 
        /// (therefore, the identifier associated with each JSON object).
        /// </summary>
        public string ExternalId { get; set; }

        /// <summary>
        /// The title refers to the name of a victual or beverage served by a specific eatery.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The quantity of payment required in exchange for a specific item in the menu.
        /// </summary>
        public double Price { get; set; }

        /// <summary>
        /// A medium of exchange used by one or several countries. 
        /// For instance, EUR is used across European countries, including Malta since 2008. 
        /// It is safe to assume that the web application may be used from a country using a different currency,
        /// therefore it is always wise to take currency-agnosticism into consideration.
        /// </summary>
        public string Currency { get; set; }

        /// <summary>
        /// This attribute acts as a foreign key as it stores a value representing an identifier from the Restaurant table (which is a foreign table related to MenuItem). 
        /// Intrinsically, it will be used to establish a one-to-many relationship between Restaurant and MenuItem 
        /// whereby one restaurant can serve many menu items, but that menu item can only be served in a single eatery.
        /// </summary>
        public int RestaurantId { get; set; }

        /// <summary>
        /// Denotes whether the menu item has been approved by the owner of the restaurant.
        /// If approved, it can be displayed in the public catalogue.
        /// </summary>
        public bool IsApproved { get; set; }
        #endregion
    }
}