using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models
{
    /// <summary>
    /// A model class representing a restaurant whereby each instance of thereof requires approval of the website administrator before it can be displayed on the public catalogue.
    /// </summary>
    public class Restaurant
    {
        #region Definition of the attributes that constitute a restaurant (such as the where the eatery is located, a general description, point of contact, and email address).
        /// <summary>
        /// Stores an integer automatically generated by Entity Framework Core by means of IDENTITY. 
        /// This helps uniquely identify each instance of Restaurant in the database.
        /// By attaching the [DatabaseGenerated(DatabaseGeneratedOption.Identity)] annotation above the property definition, 
        /// Entity Framework Core will generate a number, starting from 1 and increments by 1 for each new row.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// This is not to be confused with the Id attribute. 
        /// The former denotes how instances will be uniquely identified in the SQL Server database.
        /// Whereas ExternalId stores the value associated with the "id" key in the JSON file 
        /// (therefore, the identifier associated with each JSON object).
        /// </summary>
        public string ExternalId { get; set; }

        /// <summary>
        /// A rather self-explanatory attribute storing the name of the eatery.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// A brief description of the eatery; mainly used to indicate what cuisine the eatery specialises in, 
        /// as well as to highlight unique selling points (what sets a restaurant apart from others).
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Stores the email address of the owner of the restaurant. 
        /// This email address, available within Restaurant navigational property within a specific instance of type MenuItem, 
        /// will be used to approve a menu item associated with the owner's restaurant, 
        /// if and only if the email address of the authenticated user is equal to the email address bound to the former instance.
        /// </summary>
        public string OwnerEmailAddress { get; set; }

        /// <summary>
        /// Stores the location in which the eatery is based, comprising of a door number/name followed by the street address and the locality.
        /// </summary>
        public string Address { get; set; }

        /// <summary>
        /// Stores the phone number which serves as a point of contact in the events of queries and bookings.
        /// </summary>
        public string Phone { get; set; }

        /// <summary>
        /// Denotes whether the restaurant has been approved by the website administrator.
        /// If approved, it can be displayed on the public catalogue.
        /// </summary>
        public bool IsApproved { get; set; }
        #endregion
    }
}